name: Deploy CDK App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1

jobs:
  synth-cdk:
    name: Synthesize CDK App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Deploy Environment
        uses: ./.github/actions/setup_deploy_env

      - name: Synthesize CDK App
        run: cdk synth

  deploy-cdk:
    name: Deploy CDK App
    runs-on: ubuntu-latest
    needs: synth-cdk
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Deploy Environment
        uses: ./.github/actions/setup_deploy_env

      - name: Deploy CDK App
        run: cdk deploy --all --require-approval never
