name: Deploy CDK App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  synth-cdk:
    name: Synthesize CDK App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Deploy Environment
        uses: ./github/actions/setup_deploy_env

      - name: Synthesize CDK App
        run: cdk synth

  deploy-cdk:
    name: Deploy CDK App
    runs-on: ubuntu-latest
    needs: synth-cdk
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Deploy Environment
        uses: ./github/actions/setup_deploy_env

      - name: Deploy CDK App
        run: cdk deploy --all --require-approval never
