name: Deploy Nextjs App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-nextjs:
    name: Build Next.js App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci
        working-directory: frontend

      - name: Run Tests
        run: npm test
        working-directory: frontend

      - name: Build App
        run: npm run build
        working-directory: frontend

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: frontend/out

  deploy-nextjs:
    name: Sync Files to S3
    runs-on: ubuntu-latest
    needs: build-nextjs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: frontend/out

      - name: Get CloudFront Distribution ID
        id: get_cloudfront_distribution_id
        run: |
          DISTRIBUTION_ID=$(aws ssm get-parameter --name "/skyworkz/cloudfront/distribution-id" --query "Parameter.Value" --output text)
          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT

      - name: Test output
        run: |
          echo ${{ steps.get_cloudfront_distribution_id.outputs.DISTRIBUTION_ID }}

      # - name: Sync Files to S3
      #   run: |
      #     aws s3 sync frontend/out/ s3://skyworkz-frontend --delete

      # - name: Invalidate CloudFront Cache
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ steps.get_cloudfront_distribution_id.outputs.DISTRIBUTION_ID }} --paths "/*"
