name: Build App and Deploy CDK

on:
  push:
    branches:
      - main

jobs:
  build-nextjs:
    name: Build Next.js App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Next.js App
        run: npm run build
        working-directory: frontend

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: frontend/out

  deploy-cdk:
    name: Deploy CDK Stack
    runs-on: ubuntu-latest
    needs: build-nextjs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy CDK Stack
        run: cdk deploy --all --require-approval never
